### ISSUE TITLE
alignment CFG dev team <> embrio

### ISSUE THREAD

**Issue by sandford-ch** [embrio-tech/centrifuge-development#12]
- alignment of CFG dev team code development and dashboards produced by Embrio (Frontend alignment)

**Comment by filo87** [comment]
TODOS:
- Embrio looks into centrifuge.js and comes up with proposal how it make sense to integrate it into CFG UI App and insights https://github.com/centrifuge/apps/tree/main/centrifuge-js
- Follow up tirh onfinality for SubQL node query limitations
