### ISSUE TITLE
post progress to CFG forum and discord channel

### ISSUE THREAD

**Issue by sandford-ch** [embrio-tech/centrifuge-development#13]
- [x] Introduce Embrio as contributors to CFG
- [ ] Share relevant progress (i.e. highlights) on a monthly basis (more or less) -> recycle sprint materials
- Forum: https://gov.centrifuge.io/c/product/17
- Discord: https://discord.com/channels/805795848432779315/925436212578246668

**Comment by filo87** [comment]
Announcement post formulation: https://hackmd.io/@embrio/SJ3lG_Y9q
