### ISSUE TITLE
provide meta data and static files

### ISSUE THREAD

**Issue by tibohei** [embrio-tech/centrifuge-development#4]
### User story

> **As** dashboard viewer  
**I want** to see additional information about for example pools  
**So that** I can put charts and values into context.

### Acceptance criteria

- [ ] Concept: how to provide meta data (e.g. pool discription, website) and static files (e.g. pool logos)?
- [ ] Concept: how to update meta data and static files, when a new pool is created?

**Comment by sandford-ch** [comment]
already done
